const branches = [
    "3way Communications Ltd",
    "SLOT HQ - (84 Obafemi Awolowo Way, Ikeja, Lagos)",
    "ABUJA 1 BRANCH - (Suite C16/17 New Bannex Plaza Aminu Kano Crescent, Wuse 2. Abuja)",
    "IKEJA- MEDICAL RD - (2B Medical Road Ikeja Lagos)",
    "OPEBI BRANCH - (19 Opebi Road, Awosika B/Stop Ikeja)",
    "COMPUTER VILLAGE BRANCH - (15/19 Ola-Ayeni Street, Ikeja Lagos)",
    "IKEJA CITY MALL BRANCH - (Alausa Ikeja)",
    "VICTORIA ISLAND 1 - (13A Saka Tinubu Street, Victoria Island, Lagos)",
    "VICTORIA ISLAND 2 - (1296, Akin Adesola Street, VI- Lagos)",
    "EGBEDA AKOWONJO BRANCH - (39 Shasha Road, Akowonjo- Egbeda, Lagos)",
    "SURULERE BRANCH - (67, Adeniran Ogunsanya Street, Surulere)",
    "OKOTA BRANCH - (160 Okota Road, Cele Bus-Stop)",
    "ABUJA 2 BRANCH - (Plot 466, Ahmadu Bello Way Garki, Beside Eddy-Vic Hotel)",
    "BENIN BRANCH 1 - (89 Ekenwan Road, Beside Uba, Benin City)",
    "BENIN BRANCH 2 - (70, Airport Road, By Akenzua Junction, Benin City)",
    "OYINGBO EBUTE META BRANCH - (Tantalizes Building, 73 Murtala Muhammed Way, Oyingbo, Ebute Meta Lagos)",
    "AJAH BRANCH - (Former Aquinos Building, Berger Bus Stop Ajah Lagos)",
    "AJAH BRANCH 2 - (No 1A Addo Road Ajah. Close To Ajah. It's Opposite Olumegbon's Palace At Ado Road Close To Ajah Roundabout Lagos)",
    "LEKKI 1 BRANCH - (Ologolo Junction, Agungi, Lekki Epe Expressway, Lekki Lagos)",
    "LEKKI 2 BRANCH - (Brasas Plaza, No 16 Victoria Arobieke Street. Along Admiralty Road. Lekki Phase 1)",
    "ABEOKUTA BRANCH - (10 Lalubu Street, Oke-Ilewo, Abeokuta)",
    "WARRI BRANCH - (300 Efurun, Sapele Road, By Refinery Rd. Junction, Efurun, Warri)",
    "IFE BRANCH - (41, Ibadan Road. Mayfair Area. Ile-Ife)",
    "KETU BRANCH - (465 Ikorodu Road, Ketu Bus Stop, Lagos)",
    "SOMOLU BRANCH - (33, Fola Agoro Street, Somolu Yaba. Lagos State)",
    "IKOTUN BRANCH - (37 Idimu Road, Ikotun Lagos. Opposite Idimu Ikotun)",
    "OJODU BRANCH - (No 2 Adejokun Street, Isheri Magodo Road, Before Isheri Police Station, Isheri Ojodu Berger)",
    "OWERRI BRANCH - (68 Wetheral Road, Ikenegbu Junction, Owerri)",
    "OWERRI BRANCH 2 - (Ikenegbu Plaza By Maris Junction, Owerri, Imo State)",
    "NNEWI BRANCH - (8 Oraifite Road (Beside UBA), Nwanyi Imo Bus Stop, Nnewi)",
    "ENUGU BRANCH - (56 Okpara Avenue, Enugu)",
    "ABULE-EGBA BRANCH - (Samar Filling Station Beside Just Right Oja-Oba, Abule-Egba)",
    "ABA BRANCH - (120A Aba Owerri Road Beside Aba State Polytechnic)",
    "ABA BRANCH 2 - (30, Saint Michaels Road Aba, Abia State)",
    "ALABA BRANCH - (124, Olojo Drive, After Ojo Local Govt, Transformer Bus Stop, Alaba)",
    "FESTIVAL MALL BRANCH - (Shop 8 Festival Mall, Festac-Town Lagos)",
    "LAGOS AIRPORT - (MM1, Murtala Muhammed Local Airport Ikeja, Lagos)",
    "APAPA BRANCH - (3 Caulcrick Road, Off Kofo Ayobami, Apapa, Lagos State)",
    "FESTAC BRANCH - (51 ROAD, 512 Junctions, Festac Town Lagos)",
    "OSHODI BRANCH - (The Nigeria Army Arena. Arena Complex, Shop C5, 01, 02, 19, & 20, Bolade Bus-Stop, Oshodi, Lagos)",
    "PORTHARCOURT BRANCH 4 - (Plot 216 Aba Road Opposite, First Bank, First Artillery, PH)",
    "PORTHARCOURT BRANCH 3 - (NO. 172, Waterline Aba Road PH)",
    "PORTHARCOURT BRANCH 2 - (244 Abacha Road, GRA Phase 3 PH)",
    "ORELOPE, EGBEDA - (107, Egbeda – Idimu Road, Orelope Bus-Stop, GB Supermarket, Egbeda)",
    "AKURE BRANCH - (33, Oyemekun Road Opposite WEMA Bank, Akure, Ondo State)",
    "CALABAR BRANCH - (18 Ndidem Usiang Iso Beside Lions Club Park, Calabar)",
    "ISOLO BRANCH - (NO 26, Isolo Way, Beside Heritage Bank Ajao Estate, Airport Road, – Isolo Lagos)",
    "MARINA BRANCH - (A.G Leventis Building – 43 Marina Road, Marina)",
    "ILORIN BRANCH 1 - (27 Murtala Muhammed Way)",
    "OSOGBO BRANCH - (No 1 Woleola Estate, Opp Premier Lotto Main Office, 7 Up, Ogo-Oluwa Area, Osogbo, Osun State)",
    "AGBARA BRANCH - (KM 13, Agbara Expressway. De Sholly Busstop Odofa, Agbara)",
    "LAWANSON BRANCH - (No 1, Lawanson Road, OANDO Filling Station, Surulere, Lagos State)",
    "GBAGADA BRANCH - (No. 12 Diya Street, Beside Guaranty Trust Bank, Ifako/Gbagada Lagos)",
    "IBADAN BRANCH - (No, 121 Iwo Road Abayomi Busstop, Simisola House Ibadan)",
    "ONITSHA BRANCH - (49, New Market Road Opp 9 Mobile Onitsha By Iboku Junction)",
    "IKORODU BRANCH - (75, Lagos Road Ikorudu)",
    "SABO YABA BRANCH - (339A Herbert Macaulay Street Sabo Bus Stop, Yaba Lagos)",
    "SANGOTEDO BRANCH - (KM 42, Lekki Epe Expressway, Corner Busstop, Opposite Oando Filling Station Beside Redeem Church, Sangotedo)",
    "ASABA BRANCH - (287 Nnebuisi Road Asaba, Delta State)",
    "ASABA BRANCH 2 - (4 Okpanam Road, Beside Southgate Asaba, Delta State)",
    "BARIGA BRANCH - (24 Olaide Bustop Bariga)",
    "ADO EKITI BRANCH - (Adebayo Estate, Former Esku Health Centre Beside Energy Petrol Station, Adebayo Road)",
    "UYO - (43 Oron Road By Paul Bassey Uyo)",
    "SLOT LAKOWE STORE - (A & M Plaza, KM 42 Lekki Epe Expressway, Adeba Bus Stop, Lakowe Lagos)",
    "OJODU BERGER - (Amram House, Plot 1 Ogunnusi Road, Ojodu Berger Bus Stop, Lagos)",
    "IYANA IPAJA - (64, Ipaja-Idimu Alagutan Bus Stop, Iyana Ipaja Lagos)",
    "SATELLITE TOWN - (408, Old Ojo Road, Tantalizer Building, Abule Ado Satellite Town Lagos)",
    "IBAFO BRANCH - (KM 47, Lagos-Ibadan Express Way Ibafo)",
    "OTA BRANCH - (GB SUPERMARKET OPPOSITE IGANMODE GRAMMER SCHOOL, OJU-ORE OTA)",
    "UMUAHIA BRANCH - (1 OHAFIA ROAD, UMUAHIA)",
    "SAPELE BRANCH - (NO 30, CEMENTARY ROAD, SAPELE, DELTA STATE)",
    "UROMI BRANCH - (KM 2 NEW AGBOR ROAD, BY OBADAN JUNCTION( RAINOIL FILLING STATION) UROMI EDO STATE)",
    "OKOKOMAIKO BRANCH - (No, 1 Kenberi Road Okokomaiko Bus Stop, Badagary Express Way)",
    "OGUDU STORE - (99 Ogudu GRA Road Ojota Lagos State)",
    "IKORODU 2 - (50 Isawo Road Agric Busstop Ikorodu. @ NNPC Filling Station)",
    "ALAGBOLE - (Alagbole Busstop, Opposite MRS Filling Station Alagbole-Ajuwon Road, Ogun State)",
    "SPORTY ENYO FUEL STATION - (Lasu Road, Igando Last Bustop)",
    "SPORTY AP FUEL STATION - (21 Road Festac)",
    "SPORTY NACHO - (After SAHCO Diplomatic Car Park NAHCO)",
    "SPORTY MURTALA MOHAMMED AIRPORT MMA1 - (Alpha Departure Hall)",
    "SPORTY SAKA TINUBU VI1 - (13A Saka Tinubu Street, Victoria Island, Lagos)",
    "SPORTY IKORODU - (465 Ikorodu Road, Ketu Bus Stop, Lagos)",
    "SLOT BENIN 3 - (No. 207 Ugbowo Lagos Road, Benin City, Edo)"
];


export default branches;